set up database initial structure
alicemcneil/portfolio-cms pull request #1
Opened 2019-03-15 15:38 UTC by alicemcneil

2019-03-15 15:50 UTC, mporam requested changes
please add a comment about what project_title is for

2019-03-15 16:31 UTC, alecorra reviewed
for me it's ok

2019-03-15 16:51 UTC, mporam approved these changes

2019-03-18 14:52 UTC, Liliya-V commented on html/index.php
> +        foreach ($results as $result) {
i think here should be a function to check if $results is empty or not

2019-03-18 16:40 UTC, merged